export default {
	login: 'Miesztex',
	id: 78495100,
	node_id: 'MDQ6VXNlcjc4NDk1MTAw',
	avatar_url: 'https://avatars.githubusercontent.com/u/78495100?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/Miesztex',
	html_url: 'https://github.com/Miesztex',
	followers_url: 'https://api.github.com/users/Miesztex/followers',
	following_url: 'https://api.github.com/users/Miesztex/following{/other_user}',
	gists_url: 'https://api.github.com/users/Miesztex/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/Miesztex/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/Miesztex/subscriptions',
	organizations_url: 'https://api.github.com/users/Miesztex/orgs',
	repos_url: 'https://api.github.com/users/Miesztex/repos',
	events_url: 'https://api.github.com/users/Miesztex/events{/privacy}',
	received_events_url: 'https://api.github.com/users/Miesztex/received_events',
	type: 'User',
	site_admin: false,
	name: 'Mieszko Krzyżański',
	company: null,
	blog: '',
	location: 'Wrocław, PL',
	email: null,
	hireable: null,
	bio: '#med student\r\n#JS admirer',
	twitter_username: null,
	public_repos: 3,
	public_gists: 0,
	followers: 0,
	following: 1,
	created_at: '2021-02-03T16:06:21Z',
	updated_at: '2021-03-19T11:42:56Z',
};
